name: transcritor
description: "An app to convert speech to text"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0-52.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.3.1
  flutter_native_splash: ^2.3.9
  flutter_riverpod: ^2.4.9
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  go_router: ^13.0.1

flutter_native_splash:
  color: '#212121'
  image: assets/images/logo.png
  icon_background_color: "#FFFFFF"
  android_12:
    color: '#212121'
    image: assets/images/logo.png
    icon_background_color: "#FFFFFF"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/transcritor-logo.png
    - assets/images/logo.png
    - assets/images/onboarding-img-01.png
    - assets/images/onboarding-img-02.png
    - assets/images/correction-image.jpg
    - assets/images/recorder-image.jpg
    - assets/images/translate-image.jpg
    - assets/images/auth-img-01.jpg
    - assets/images/auth-img-02.jpg
    - assets/images/auth-img-03.jpg
    - assets/images/auth-img-04.jpg
    - assets/images/auth-img-05.jpg
