name: transcritor
description: "An app to convert speech to text"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0-52.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.3.1
  flutter_native_splash: ^2.3.9
  flutter_riverpod: ^2.4.9
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  go_router: ^13.0.1
  validatorless: ^1.2.3
  intl_phone_field: ^3.2.0
  http: ^1.2.0
  flutter_secure_storage: ^4.2.1
  dartz: ^0.10.1
  adaptive_action_sheet: ^2.0.3
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  faker: ^2.1.0
  collection: ^1.18.0
  just_audio: ^0.9.36
  just_audio_background: ^0.0.1-beta.11
  rxdart: ^0.27.7
  audio_video_progress_bar: ^2.0.2
  file_picker: ^8.0.0+1
  slide_to_act: ^2.0.2
  record: ^5.0.4

flutter_native_splash:
  color: '#212121'
  image: assets/images/logo.png
  icon_background_color: "#FFFFFF"
  android_12:
    color: '#212121'
    image: assets/images/logo.png
    icon_background_color: "#FFFFFF"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/transcritor-logo.png
    - assets/images/logo.png
    - assets/images/onboarding-img-01.png
    - assets/images/onboarding-img-02.png
    - assets/images/onboarding-img-03.jpg
    - assets/images/onboarding-img-04.jpg
    - assets/images/onboarding-img-05.jpg
    - assets/images/correction-image.jpg
    - assets/images/recorder-image.jpg
    - assets/images/translate-image.jpg
    - assets/images/auth-img-01.jpg
    - assets/images/auth-img-02.jpg
    - assets/images/auth-img-03.jpg
    - assets/images/auth-img-04.jpg
    - assets/images/auth-img-05.jpg
    - assets/images/auth-img-06.jpg
