name: transcritor
description: "An app to convert speech to text"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0-52.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.3.1
  flutter_native_splash: ^2.3.9
  flutter_riverpod: ^2.4.9
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
