name: transcritor
description: "An app to convert speech to text"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0-52.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.3.1
  flutter_native_splash: ^2.3.9
  flutter_riverpod: ^2.4.9
  intl: ^0.19.0

flutter_native_splash:
  color: '#212121'
  image: assets/images/logo.png
  android_12:
    color: '#212121'
    image: assets/images/logo.png
    icon_background_color: "#FFFFFF"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/transcritor-logo.png
    - assets/images/logo.png
